### ISSUE TITLE
Does it able to read csv dataset and perform data analysis?

### ISSUE THREAD

**Issue by hhy-joseph** [SeungyounShin/Llama2-Code-Interpreter#6]
And run code for data visualizations

**Comment by SeungyounShin** [comment]
You can indeed include user content in the prompt by using the syntax `f"{user_content}\nUser Uploaded File: {'./tmp/file.csv'}"`. This feature is especially beneficial as it enables the seamless construction of datasets and supports Supervised Fine-Tuning (SFT) on LLama2 with data generated by GPT-4.  #1

**Comment by hhy-joseph** [comment]
Can we limit the Internet access ability? Let say make the model search answer from my DB instead of the Internet. Thank you!

**Comment by itsPreto** [comment]
hey @SeungyounShin I've recently implemented a similar library like yours that it's basically baked into [llama.cpp](https://github.com/ggerganov/llama.cpp) and it uses a lot of the same techniques you have have implemented here.

[Here is the project](https://github.com/itsPreto/baby-llama.pycpp) in case you are interesting in a possible collab- 

Also-- I'm curious to know how you handled the prompts that require first examining a file's content and ingesting a sample of it for a more accurate/tailored completion.

**Comment by itsPreto** [comment]
@SeungyounShin that makes a lot of sense! I'll be looking to implement the same this weekend.

I was also thinking about the possibility of training or fine-tuning a smaller model (similar to replit-v2-3B) that's specialized in function calling. 

This way the ability to open and inspect files could be treated as a tool available! I think it would compliment the bigger models extremely well.

**Comment by hhy-joseph** [comment]
Sorry for asking again, might I know which file I should put: f"{user_content}\nUser Uploaded File: {'./tmp/file.csv'}" to allow user upload csv? Thank you!

**Comment by SeungyounShin** [comment]
@hhy-joseph 

To integrate the CSV upload feature using the mentioned format, you'd want to modify the section of code at [chatbot.py Line 27C49-L27C56](https://github.com/SeungyounShin/Llama2-Code-Interpreter/blob/b7cb9a1460f1c35959b9f0aa71640664d6b32a11/chatbot.py#L27C49-L27C56). You can adjust the msg variable accordingly.

However, it's crucial to remember that just revising this line might not be enough. The full integration will require adjustments in the Gradio UI to handle the CSV file uploads. I'm planning on updating this aspect in the near future to make it more seamless.

Thanks for bringing this to attention, and stay tuned for the updates!

**Comment by Jipok** [comment]
@itsPreto
Sorry for writing here. But I don't know how else to contact you. Your project is good, but publishing on github in the current version has huge disadvantages. Since this is a fork you don't have any issues or discussions, how can a person ask a question/suggestion/improvement? I even have to write my current message in the issues of a third-party project. And if I had not accidentally stumbled upon you here, I would not have been able to write to you at all. It is almost impossible to find your project in the github search results, both because it is a fork and because you absolutely did not change the original description from llama.cpp. No tags.
In general, I suggest that you create a new repository with a suitable description and a set of tags. Or open [old one](https://github.com/itsPreto/baby-code). In this case, I think you will be successful in attracting people to the project.

**Comment by itsPreto** [comment]
@Jipok thanks for the feedback-- and sorry for hijacking this thread @SeungyounShin 

- Why a fork? Simply put, llama.cpp provides the best out-of-the-box inferencing for cpu/gpu across many operating systems. Forking it lets me *almost* seamlessly pull in any updates from the upstream as llama.cpp is heavily under development and always getting tons of improvements/breaking changes. 

- Unchanged project description: this is just because it's not possible to alter the project description of a forked project-- not sure if there are workarounds to this limitation but I'm not aware of any.

I'll look into refactoring the project to just use the published/released tags instead of baking my project directly into their library.

**Comment by Jipok** [comment]
> Why a fork? Simply put, llama.cpp provides the best out-of-the-box inferencing for cpu/gpu across many operating systems. Forking it lets me almost seamlessly pull in any updates from the upstream as llama.cpp is heavily under development and always getting tons of improvements/breaking changes.

I get it. I'm not saying anything about the implementation of your code. I meant "why are you using the fork feature on github itself"? Make it out as a separate project(or open an old one) and just use basic `git remote add upstream git@github.com:ggerganov/llama.cpp.git` locally and `git pull upstream && git push master`

**Comment by SeungyounShin** [comment]
close for temporarily
